[project]
name = "sis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-allauth>=65.11.2",
    "django-guardian>=3.2.0",
    "django-ninja>=1.4.3",
    "django-unfold>=0.67.0",
]
